//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTunki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactos
    {
        public contactos()
        {
            this.pagocontactos = new HashSet<pagocontactos>();
        }
    
        public int idcontacto { get; set; }
        public string nombrecontacto { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<pagocontactos> pagocontactos { get; set; }
    }
}
