//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTunki.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tunkiEntities1 : DbContext
    {
        public tunkiEntities1()
            : base("name=tunkiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<contactos> contactos { get; set; }
        public DbSet<mediopagos> mediopagos { get; set; }
        public DbSet<operadores> operadores { get; set; }
        public DbSet<pagocontactos> pagocontactos { get; set; }
        public DbSet<recargacelulares> recargacelulares { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
