//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTunki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operadores
    {
        public operadores()
        {
            this.recargacelulares = new HashSet<recargacelulares>();
        }
    
        public int idoperador { get; set; }
        public string nombreoperador { get; set; }
    
        public virtual ICollection<recargacelulares> recargacelulares { get; set; }
    }
}
