//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTunki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagocontactos
    {
        public int idpagocontacto { get; set; }
        public decimal saldo { get; set; }
        public string codigodeoperacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> monto { get; set; }
        public int idcontacto { get; set; }
        public int idusuarios { get; set; }
        public int idmediopago { get; set; }
    
        public virtual contactos contactos { get; set; }
        public virtual mediopagos mediopagos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
