//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTunki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recargacelulares
    {
        public int idrecargacelular { get; set; }
        public decimal telefono { get; set; }
        public decimal monto { get; set; }
        public int idoperador { get; set; }
        public int idusuario { get; set; }
        public int idmediopago { get; set; }
    
        public virtual mediopagos mediopagos { get; set; }
        public virtual operadores operadores { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
