//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTunki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.pagocontactos = new HashSet<pagocontactos>();
            this.recargacelulares = new HashSet<recargacelulares>();
        }
    
        public int idusuario { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public Nullable<decimal> saldo { get; set; }
    
        public virtual ICollection<pagocontactos> pagocontactos { get; set; }
        public virtual ICollection<recargacelulares> recargacelulares { get; set; }
    }
}
